server:
  port: 5002
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

app:
  gc-two:
    url: http://localhost:5003
    name: gc-two

logging:
  level:
    com.example: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        slidingWindowSize: 30
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowType: COUNT_BASED #COUNT_BASED TIME_BASED
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 30s
        failureRateThreshold: 80
  retry:
    instances:
      retryInstance:
        maxRetryAttempts: 3
        waitDuration: 5s

#        slidingWindowSize: 30 duas chamas e na janela de 30 segundos
#        permittedNumberOfCallsInHalfOpenState: 2
#        slidingWindowType: TIME_BASED
#        minimumNumberOfCalls: 2 vai esperar duas chamadas serem feitas para el começar a analisar as requests
#        waitDurationInOpenState: 30s
#        failureRateThreshold: 80