server:
  port: 5002
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

app:
  gc-two:
    url: http://localhost:5003
    name: gc-two

logging:
  level:
    com.example: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

resilience4j:
  retry:
    instances:
      retryInstance:
        maxRetryAttempts: 3
        waitDuration: 5s